apiVersion: v1
kind: Service

metadata:
  name: fitness-tracker-service

spec:
  type: LoadBalancer

  selector:
    app: fitness-tracker

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000